run:
	python3 mt.py

question_1:
	python3 mt.py q1
	
question_2:
	python3 mt.py q2
	
question_3:
	python3 mt.py q3
	
question_5:
	python3 mt.py q5
	
question_6:
	python3 mt.py q6
	
question_7:
	python3 mt.py q7

question_8:
	python3 mt.py q8